### ISSUE TITLE
error bundle exec rake db:setup

### ISSUE THREAD

**Issue by wozzi** [Apollo-IT/peatio_current#4]
Hello,

get this error while setting up. Not sure whats the problem. following the documentation. Does anyone know the issue?

prod@WozExc:~/peatio$ bundle exec rake db:setup
DEPRECATION WARNING: The factory_girl gem is deprecated. Please upgrade to facto                              ry_bot. See https://github.com/thoughtbot/factory_bot/blob/v4.9.0/UPGRADE_FROM_F                              ACTORY_GIRL.md for further instructions. (called from <top (required)> at /home/                              prod/peatio/config/application.rb:12)
/home/prod/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/figaro-1.1.1/lib/figar                              o/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Fi                              garo configuration. 65910 was converted to "65910". (StructuredWarnings::Standar                              dWarning)
/home/prod/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/figaro-1.1.1/lib/figar                              o/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Fi                              garo configuration. true was converted to "true". (StructuredWarnings::StandardW                              arning)
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'exchange_development.docum                              ents' doesn't exist: SHOW FULL FIELDS FROM `documents`
/home/prod/peatio/app/models/document.rb:3:in `<class:Document>'
/home/prod/peatio/app/models/document.rb:1:in `<top (required)>'
/home/prod/peatio/config/routes.rb:1:in `<top (required)>'
/home/prod/peatio/config/environment.rb:5:in `<top (required)>'
/home/prod/.rbenv/versions/2.2.8/bin/bundle:23:in `load'
/home/prod/.rbenv/versions/2.2.8/bin/bundle:23:in `<main>'

Caused by:
Mysql2::Error: Table 'exchange_development.documents' doesn't exist
/home/prod/peatio/app/models/document.rb:3:in `<class:Document>'
/home/prod/peatio/app/models/document.rb:1:in `<top (required)>'
/home/prod/peatio/config/routes.rb:1:in `<top (required)>'
/home/prod/peatio/config/environment.rb:5:in `<top (required)>'
/home/prod/.rbenv/versions/2.2.8/bin/bundle:23:in `load'
/home/prod/.rbenv/versions/2.2.8/bin/bundle:23:in `<main>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => environment
(See full trace by running task with --trace)

**Comment by nantestdevoloper** [comment]
getting same error 

Caused by:
Mysql2::Error: Table 'apollo_exchange_development.documents' doesn't exist
/home/.rvm/gems/ruby-2.2.8/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `query'
/home/.rvm/gems/ruby-2.2.8/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
/home/.rvm/gems/ruby-2.2.8/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/home/.rvm/gems/ruby-2.2.8/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/.rvm/gems/ruby-2.2.8/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/home/.rvm/gems/ruby-2.2.8/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
/home/.rvm/gems/ruby-2.2.8/gems/activerecord-4.2.8/lib/active_record/connection_adapters/mysql2_adapter.rb:225:in `execute'

**Comment by TranBaVinhSon** [comment]
Same error:
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'exchange_development.documents' doesn't exist: SHOW FULL FIELDS FROM `documents`
...
...
...
Caused by:
Mysql2::Error: Table 'exchange_development.documents' doesn't exist

**Comment by klima911** [comment]
me too, the same error.  .documents doesn't exist

**Comment by Apollo-IT** [comment]
hi, This repository is WIP.
it's under upgrading.
It will be completed soon.
Until that, we can meet some issues.

**Comment by Nolaan** [comment]
@Apollo-IT So why you tell people to use your repo then!!!
:angry:
